import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/provider/ReduxProvider";
import { TRootLayout } from "@/types/RootType";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<TRootLayout>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <ReduxProvider>
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </ReduxProvider>
      </body>
    </html>
  );
}
